baseURL = "http://theatwatergroup.com/"
languageCode = "en-us"
title = "THC Staffing Group | The Revolution is Hiring"

## Main Menu

  [[menu.main]]
    name = "Employers"
    identifier = "employers"
    weight = 100
    url = "/employers/"
  [[menu.main]]
    name = "Candidates"
    identifier = "candidates"
    weight = 200
    url = "/candidates/"
  [[menu.main]]
    name = "About"
    weight = 300
    identifier = "about"
    url = "/about/"
